/**
 * StatusCode defines the status code that may returns by the {TableManager}
 */
public enum StatusCode {

  SUCCESS,
  TABLE_ALREADY_EXISTS,
  TABLE_CREATION_ATTRIBUTE_INVALID,
  TABLE_CREATION_NO_PRIMARY_KEY,
  TABLE_CREATION_PRIMARY_KEY_NOT_FOUND,
  ATTRIBUTE_TYPE_NOT_SUPPORTED,
  TABLE_NOT_FOUND,
  ATTRIBUTE_ALREADY_EXISTS,
  ATTRIBUTE_NOT_FOUND

}
